### ISSUE TITLE
Browser console error

### ISSUE THREAD

**Issue by paragkamra** [mlazarov/ddos-stress#3]
Hey I have configured the DDoS-Stress tool. so, i started node.js and server.js after specify the configurations. in node.js it is connected to server and in server.js new node connected! 1 ready. This is the mesage i am receving, but when i open the browser only single line json code is renedering and in server.js i am geeting this message "One Node less :( 0 still here" 

below is the screenshot which you can check.
![_1](https://user-images.githubusercontent.com/28391895/29604045-d7fbb96c-8803-11e7-82ff-4268aa523d47.png)

**Comment by mlazarov** [comment]
Hi paragkamra!

To help you I need to know what changes did you do on the app?
