### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by justachillinguy** [mlazarov/ddos-stress#5]
[This package](https://www.jsdelivr.com/package/npm/ddos-stress) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by mlazarov** [comment]
Thanks, But No Thanks.

**Comment by justachillinguy** [comment]
Ok, thx
